//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class number_plate
    {
        public int id { get; set; }
        public int id_bike { get; set; }
        public string number { get; set; }
        public Nullable<bool> available { get; set; }
        public Nullable<int> id_rent { get; set; }
    
        public virtual bike bikes { get; set; }
    }
}
